import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-schedules-listing-page',
  templateUrl: './schedules-listing-page.component.html',
  styleUrls: ['./schedules-listing-page.component.css']
})
export class SchedulesListingPageComponent implements OnInit {

  scheduledList: any[] =[
    {
       "flightScheduleId":2,
       "departureTime":"2021-11-20T10:00:00",
       "arrivalTime":"2021-11-20T07:00:00",
       "scheduledStartDate":"2021-11-20T10:00:00",
       "scheduledEndDate":"2021-11-30T23:59:00",
       "flight":{
          "flightId":3,
          "flightName":"Deccan CS1",
          "businessSeats":20,
          "nonBusinessSeats":15,
          "businessSeatCost":9000.0,
          "nonBusinessSeatCost":3000.0,
          "isActive":1,
          "airline":{
             "airlineId":2,
             "airlineName":"Decaan",
             "iaia":"DC",
             "isActive":0
          },
          "meals":[
             {
                "mealId":1,
                "mealType":"veg"
             },
             {
                "mealId":2,
                "mealType":"Non-veg"
             }
          ],
          "flightSeats":[
             {
                "flightSeatId":1,
                "flightSeatNumber":"B1",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":2,
                "flightSeatNumber":"B2",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":3,
                "flightSeatNumber":"B3",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":4,
                "flightSeatNumber":"B4",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":5,
                "flightSeatNumber":"B5",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":6,
                "flightSeatNumber":"B6",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":7,
                "flightSeatNumber":"B7",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":8,
                "flightSeatNumber":"B8",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":9,
                "flightSeatNumber":"B9",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":10,
                "flightSeatNumber":"B10",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":11,
                "flightSeatNumber":"B11",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":12,
                "flightSeatNumber":"B12",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":13,
                "flightSeatNumber":"B13",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":14,
                "flightSeatNumber":"B14",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":15,
                "flightSeatNumber":"B15",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":16,
                "flightSeatNumber":"B16",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":17,
                "flightSeatNumber":"B17",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":18,
                "flightSeatNumber":"B18",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":19,
                "flightSeatNumber":"B19",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":20,
                "flightSeatNumber":"B20",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":21,
                "flightSeatNumber":"NB1",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":22,
                "flightSeatNumber":"NB2",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":23,
                "flightSeatNumber":"NB3",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":24,
                "flightSeatNumber":"NB4",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":25,
                "flightSeatNumber":"NB5",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":26,
                "flightSeatNumber":"NB6",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":27,
                "flightSeatNumber":"NB7",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":28,
                "flightSeatNumber":"NB8",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":29,
                "flightSeatNumber":"NB9",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":30,
                "flightSeatNumber":"NB10",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":31,
                "flightSeatNumber":"NB11",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":32,
                "flightSeatNumber":"NB12",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":33,
                "flightSeatNumber":"NB13",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":34,
                "flightSeatNumber":"NB14",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":35,
                "flightSeatNumber":"NB15",
                "isBusinessSeat":0
             }
          ]
       },
       "departurePlaceId":{
          "cityId":4,
          "cityName":"Coimabtore",
          "cityCode":"CJB",
          "isActive":1
       },
       "destinationPlaceId":{
          "cityId":5,
          "cityName":"Kochi",
          "cityCode":"COK",
          "isActive":1
       },
       "scheduleDays":null
    },
    {
       "flightScheduleId":4,
       "departureTime":"2021-11-20T08:00:00",
       "arrivalTime":"2021-11-20T09:00:00",
       "scheduledStartDate":"2021-11-20T10:00:00",
       "scheduledEndDate":"2021-11-30T23:59:00",
       "flight":{
          "flightId":3,
          "flightName":"Deccan CS1",
          "businessSeats":20,
          "nonBusinessSeats":15,
          "businessSeatCost":9000.0,
          "nonBusinessSeatCost":3000.0,
          "isActive":1,
          "airline":{
             "airlineId":2,
             "airlineName":"Decaan",
             "iaia":"DC",
             "isActive":0
          },
          "meals":[
             {
                "mealId":1,
                "mealType":"veg"
             },
             {
                "mealId":2,
                "mealType":"Non-veg"
             }
          ],
          "flightSeats":[
             {
                "flightSeatId":1,
                "flightSeatNumber":"B1",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":2,
                "flightSeatNumber":"B2",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":3,
                "flightSeatNumber":"B3",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":4,
                "flightSeatNumber":"B4",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":5,
                "flightSeatNumber":"B5",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":6,
                "flightSeatNumber":"B6",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":7,
                "flightSeatNumber":"B7",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":8,
                "flightSeatNumber":"B8",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":9,
                "flightSeatNumber":"B9",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":10,
                "flightSeatNumber":"B10",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":11,
                "flightSeatNumber":"B11",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":12,
                "flightSeatNumber":"B12",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":13,
                "flightSeatNumber":"B13",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":14,
                "flightSeatNumber":"B14",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":15,
                "flightSeatNumber":"B15",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":16,
                "flightSeatNumber":"B16",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":17,
                "flightSeatNumber":"B17",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":18,
                "flightSeatNumber":"B18",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":19,
                "flightSeatNumber":"B19",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":20,
                "flightSeatNumber":"B20",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":21,
                "flightSeatNumber":"NB1",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":22,
                "flightSeatNumber":"NB2",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":23,
                "flightSeatNumber":"NB3",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":24,
                "flightSeatNumber":"NB4",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":25,
                "flightSeatNumber":"NB5",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":26,
                "flightSeatNumber":"NB6",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":27,
                "flightSeatNumber":"NB7",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":28,
                "flightSeatNumber":"NB8",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":29,
                "flightSeatNumber":"NB9",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":30,
                "flightSeatNumber":"NB10",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":31,
                "flightSeatNumber":"NB11",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":32,
                "flightSeatNumber":"NB12",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":33,
                "flightSeatNumber":"NB13",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":34,
                "flightSeatNumber":"NB14",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":35,
                "flightSeatNumber":"NB15",
                "isBusinessSeat":0
             }
          ]
       },
       "departurePlaceId":{
          "cityId":1,
          "cityName":"Delhi",
          "cityCode":"DEL",
          "isActive":1
       },
       "destinationPlaceId":{
          "cityId":2,
          "cityName":"Goa",
          "cityCode":"GOI",
          "isActive":1
       },
       "scheduleDays":null
    },
    {
       "flightScheduleId":5,
       "departureTime":"2021-11-20T08:00:00",
       "arrivalTime":"2021-11-20T09:00:00",
       "scheduledStartDate":"2021-11-20T10:00:00",
       "scheduledEndDate":"2021-11-30T23:59:00",
       "flight":{
          "flightId":3,
          "flightName":"Deccan CS1",
          "businessSeats":20,
          "nonBusinessSeats":15,
          "businessSeatCost":9000.0,
          "nonBusinessSeatCost":3000.0,
          "isActive":1,
          "airline":{
             "airlineId":2,
             "airlineName":"Decaan",
             "iaia":"DC",
             "isActive":0
          },
          "meals":[
             {
                "mealId":1,
                "mealType":"veg"
             },
             {
                "mealId":2,
                "mealType":"Non-veg"
             }
          ],
          "flightSeats":[
             {
                "flightSeatId":1,
                "flightSeatNumber":"B1",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":2,
                "flightSeatNumber":"B2",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":3,
                "flightSeatNumber":"B3",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":4,
                "flightSeatNumber":"B4",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":5,
                "flightSeatNumber":"B5",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":6,
                "flightSeatNumber":"B6",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":7,
                "flightSeatNumber":"B7",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":8,
                "flightSeatNumber":"B8",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":9,
                "flightSeatNumber":"B9",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":10,
                "flightSeatNumber":"B10",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":11,
                "flightSeatNumber":"B11",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":12,
                "flightSeatNumber":"B12",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":13,
                "flightSeatNumber":"B13",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":14,
                "flightSeatNumber":"B14",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":15,
                "flightSeatNumber":"B15",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":16,
                "flightSeatNumber":"B16",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":17,
                "flightSeatNumber":"B17",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":18,
                "flightSeatNumber":"B18",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":19,
                "flightSeatNumber":"B19",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":20,
                "flightSeatNumber":"B20",
                "isBusinessSeat":1
             },
             {
                "flightSeatId":21,
                "flightSeatNumber":"NB1",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":22,
                "flightSeatNumber":"NB2",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":23,
                "flightSeatNumber":"NB3",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":24,
                "flightSeatNumber":"NB4",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":25,
                "flightSeatNumber":"NB5",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":26,
                "flightSeatNumber":"NB6",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":27,
                "flightSeatNumber":"NB7",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":28,
                "flightSeatNumber":"NB8",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":29,
                "flightSeatNumber":"NB9",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":30,
                "flightSeatNumber":"NB10",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":31,
                "flightSeatNumber":"NB11",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":32,
                "flightSeatNumber":"NB12",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":33,
                "flightSeatNumber":"NB13",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":34,
                "flightSeatNumber":"NB14",
                "isBusinessSeat":0
             },
             {
                "flightSeatId":35,
                "flightSeatNumber":"NB15",
                "isBusinessSeat":0
             }
          ]
       },
       "departurePlaceId":{
          "cityId":1,
          "cityName":"Delhi",
          "cityCode":"DEL",
          "isActive":1
       },
       "destinationPlaceId":{
          "cityId":2,
          "cityName":"Goa",
          "cityCode":"GOI",
          "isActive":1
       },
       "scheduleDays":null
    }
 ];

  constructor() { }

  ngOnInit(): void {
  }

}
